#!/usr/bin/env bash

# f-blackarch
# Find a program based on its BlackArch group name

set -e

groups=$(pacman -Sg | awk '{print $1}' | sort -u | grep '^blackarch-')

groupname=$(echo "$groups" | fzf --reverse --prompt="Select a BlackArch group: " --exact)

if [ -z "$groupname" ]; then
    echo "No group selected."
    exit 1
fi

tools=$(pacman -Sg "$groupname" | awk '{print $2}' | sort -u)

# Get descriptions
tool_descriptions=$(pacman -Qi $tools 2>/dev/null | awk -v RS='' '/^Name/{print $2": "$0}')

toolname=$(echo "$tool_descriptions" | fzf --reverse --prompt="Select a tool in $groupname: " --exact | cut -d':' -f1)
