#!/usr/bin/env sh

if [ "$#" -lt 2 ]; then
  echo "Usage: $0 <source> <outfile>"
  exit 1
fi

SOURCE="$1"
OUTFILE="$2"

tar -cf - "$SOURCE" | openssl enc -aes-256-cbc -salt -out "$OUTFILE"

if [ $? -eq 0 ]; then
  echo "Encryption successful! Encrypted file saved as: $OUTFILE"
else
  echo "Encryption failed!"
  exit 1
fi
