#!/usr/bin/env sh

#   __     _
#  / _| __| |
# | |_ / _` |
# |  _| (_| |
# |_|  \__,_|
#

# fuzzy directory finder

dir=$(find "${1:-/}" -type d 2>/dev/null | fzf-tmux -p --reverse --exact --preview 'ls -la {}') && cd "$dir"

